### ISSUE TITLE
Remove client testing?

### ISSUE THREAD

**Issue by slowli** [exonum/cryptocurrency#20]
README presently mentions testing through JavaScript code and thus mentions Node.js as a requirement (why `>= 6.9.1`, btw?). I think it may be superfluous; testing can be performed with `examples/test.sh`. This could minimize the number of entities used in the demo. Additionally, I think that client integration (and associated tests) should be a subject of another tutorial.

**Proposed solution:** remove Node.js dependency and associated client-based testing description from README.

**Comment by DenisKolodin** [comment]
@slowli I've fixed it here: https://github.com/exonum/cryptocurrency/commit/f99050e6e049965038ea949f64e10fa4f49ea8fe
Could I close this issue?
