### ISSUE TITLE
Mention libsodium dependency in README

### ISSUE THREAD

**Issue by pepyakin** [exonum/cryptocurrency#25]
The README.md states:

```markdown
To run this example you need:

* Latest [Rust](https://www.rust-lang.org/en-US/) (version 1.18.0 or above)
```

But actually, to run this example one also needs libsodium installed.
I'm on macOS and `brew install libsodium` worked for me.

**Comment by slowli** [comment]
Thanks for noticing! I think README can link to [the installation guide](http://exonum.com/doc/get-started/install/) in the docs (which mentions libsodium, among other things), but as the maintainer of the docs repo I may be biased 😃 @DenisKolodin, what do you think?

**Comment by pepyakin** [comment]
Oh, I think it would be great!
