### ISSUE TITLE
TxTransfer.info returning null

### ISSUE THREAD

**Issue by Mangman** [exonum/cryptocurrency#31]
Documentation says info() behaviour should return transaction information but it returns default Null instead.
------------------------
From https://exonum.com/doc/architecture/transactions/#info :

"Example
In the cryptocurrency service an info method of TxTransfer returns JSON with fields from, to, amount and seed."

**Comment by slowli** [comment]
Hi, thanks for noticing! The documentation was incorrect (`info` method should not be overridden in the tutorial); see exonum/exonum-doc#118 and exonum/exonum-doc#122. It's already been fixed in the documentation repository and should soon be uploaded to the website.
