### ISSUE TITLE
Wallet should stay immutable

### ISSUE THREAD

**Issue by vldm** [exonum/cryptocurrency#34]
In tutorial we have:
```
    pub fn increase(&mut self, amount: u64) {
        let balance = self.balance() + amount;
        Field::write(&balance, &mut self.raw, 40, 48);
    }

    pub fn decrease(&mut self, amount: u64) {
        let balance = self.balance() - amount;
        Field::write(&balance, &mut self.raw, 40, 48);
  }
```

This is conceptual wrong in general case. Of course its clear to change fixed sized type, but for DST, this rule isn't clear. That why `Field::write` is not a good choice for tutorial, we should rewrite it, to create a new `Wallet` each time.

**Comment by quicky84** [comment]
I direct you attention that due to the latest merge (b1c8637a20a9e9bf4d5acc33a4a1cfedece32aeb) the commit corresponding to this issue (e9fc4c9989296abce2f8dbee1491e467cf6eb5e5) has not reflection in the present code.
