### ISSUE TITLE
examples/test.sh

### ISSUE THREAD

**Issue by quicky84** [exonum/cryptocurrency#40]
`launch-server` never returns on Fedora 26.
that is, no transaction is executed, server is never killed.

manual termination does not stop the server, but rather the execution of the script.

**Comment by slowli** [comment]
Seems to be solved by #38? The relevant code is my fault; I mostly reasoned that it's enough to make it work on Travis, but this reasoning is *always* faulty 😓

**Comment by quicky84** [comment]
Yes, #38 runs well. Do not forget to list [jq](https://admin.fedoraproject.org/pkgdb/package/rpms/jq/) as dependency
